# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Leecher.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 641, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(11, 260, 611, 34))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txt_destino = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.txt_destino.setEnabled(False)
        self.txt_destino.setObjectName("txt_destino")
        self.horizontalLayout_2.addWidget(self.txt_destino)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(11, 20, 611, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txt_find = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txt_find.setObjectName("txt_find")
        self.horizontalLayout.addWidget(self.txt_find)
        self.btn_find = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_find.setObjectName("btn_find")
        self.horizontalLayout.addWidget(self.btn_find)
        self.lbl_status = QtWidgets.QLabel(self.tab1)
        self.lbl_status.setGeometry(QtCore.QRect(11, 530, 610, 31))
        self.lbl_status.setObjectName("lbl_status")
        self.btn_download = QtWidgets.QPushButton(self.tab1)
        self.btn_download.setGeometry(QtCore.QRect(10, 300, 130, 30))
        self.btn_download.setObjectName("btn_download")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 611, 180))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tbl_result = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tbl_result.setObjectName("tbl_result")
        self.tbl_result.setColumnCount(0)
        self.tbl_result.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_result)
        self.btn_stop_download = QtWidgets.QPushButton(self.tab1)
        self.btn_stop_download.setGeometry(QtCore.QRect(150, 300, 130, 30))
        self.btn_stop_download.setObjectName("btn_stop_download")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 370, 611, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.txt_log = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.txt_log.setEnabled(True)
        self.txt_log.setObjectName("txt_log")
        self.verticalLayout_2.addWidget(self.txt_log)
        self.btn_play = QtWidgets.QPushButton(self.tab1)
        self.btn_play.setGeometry(QtCore.QRect(290, 300, 120, 30))
        self.btn_play.setObjectName("btn_play")
        self.btn_graphic = QtWidgets.QPushButton(self.tab1)
        self.btn_graphic.setGeometry(QtCore.QRect(420, 300, 111, 30))
        self.btn_graphic.setObjectName("btn_graphic")
        self.chk_preview = QtWidgets.QCheckBox(self.tab1)
        self.chk_preview.setGeometry(QtCore.QRect(10, 340, 191, 22))
        self.chk_preview.setObjectName("chk_preview")
        self.tabWidget.addTab(self.tab1, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.txt_statistic = QtWidgets.QTextEdit(self.tab3)
        self.txt_statistic.setEnabled(True)
        self.txt_statistic.setGeometry(QtCore.QRect(10, 10, 621, 541))
        self.txt_statistic.setObjectName("txt_statistic")
        self.tabWidget.addTab(self.tab3, "")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cliente P2P UDP"))
        self.label_2.setText(_translate("MainWindow", "Diretório Download"))
        self.label.setText(_translate("MainWindow", "Informe nome do arquivo"))
        self.btn_find.setText(_translate("MainWindow", "Buscar"))
        self.lbl_status.setText(_translate("MainWindow", "Network P2P Status"))
        self.btn_download.setText(_translate("MainWindow", "Iniciar Download"))
        self.label_3.setText(_translate("MainWindow", "Resultado da Busca"))
        self.btn_stop_download.setText(_translate("MainWindow", "Parar Download"))
        self.label_4.setText(_translate("MainWindow", "Resumo"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.btn_graphic.setText(_translate("MainWindow", "Mostrar Gráfico"))
        self.chk_preview.setText(_translate("MainWindow", "Pré-visualização de áudio"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Busca e Download"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Estatisticas"))

